sudo: true
dist: xenial
language: python
matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.7
      env: TOXENV=flake8

install: pip install tox-travis
script: tox