dist: xenial
language: python
python:
- 3.7
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bpaulin
  password:
    secure: NzmEZGL0FfUKR+AaO9wgeYyBZeEsxOamkeY4sc7WQgHsJRy6p6JD4xR5ZbUqMhXv1cTZojYQfYMsWmitMovNsF6KenFprgxFgY4S3QgUhC08AVW+T1uzaLkp5gv/jLq5WpfDGtSB0KaKSwsi7086L6EEsUnuWtQCOdbOwkMbuEDKm/hIxFubqmTEYwo4eWChyUf9rAyG+RqeYenELVqaTiJ3joNBVr8/rFsT+Ck5HYw837y01kh+FbRBFJOkr+NCHWK2NMnQq/aTiAGAPVGqVRNt8OtPlS+q8ctdfjawDNKH2hfGcGptPv1GidMO8n4+//pCjefXgDrLfm5izc1TOGzkWK9e57/MbqOHxibPL/KpfMj6lhP5zM7O0joCqtfqcvCxwgpE28kOLuJi2DDPJbv909JpvkH3NJWtJedDR+dWcq5JlT7lQ/ut10aSFLteE9wbELcTCodG12sRb3ajXd0rncMctXapxp0uXAHpPYxdL+tFQQKA4t3TUW80HfPUdvBEmba8oIcByrxHnJbXxW3KeHMF68/3QH+9l+6Piw8WVyclW5pvVVhC74/r0K2eH7AMFFyBfSsFg+5gFk4YvT1d7hByeWqziOx22rJaH0aYuTp+4eHuRmVfpAd+TStWrZ+wSkwgjCQPa18Zjm9i1iW5X7f6XcNijzrKQQxEEmE=
  on:
    tags: true
    repo: bpaulin/brownpaperbag
    python: 3.6
